const STORE_KEY = 'loft-taxi/address';

// Route
export const ROUTE_LOADING = `${STORE_KEY}/ROUTE_LOADING`;
export const ROUTE_REQUEST = `${STORE_KEY}/ROUTE_REQUEST`;
export const ROUTE_SUCCESS = `${STORE_KEY}/ROUTE_SUCCESS`;
export const ROUTE_FAILURE = `${STORE_KEY}/ROUTE_FAILURE`;

// AddressList
export const ADDRESS_LOADING = `${STORE_KEY}/ADDRESS_LOADING`;
export const ADDRESS_LIST_REQUEST = `${STORE_KEY}/ADDRESS_LIST_REQUEST`;
export const ADDRESS_LIST_SUCCESS = `${STORE_KEY}/ADDRESS_LIST_SUCCESS`;
export const ADDRESS_LIST_FAILURE = `${STORE_KEY}/ADDRESS_LIST_FAILURE`;

export const ADDRESS_CLEAR_ERROR = `${STORE_KEY}/ADDRESS_CLEAR_ERROR`;
export const ADDRESS_RESET = `${STORE_KEY}/ADDRESS_RESET`;
